// -----------------------------------------------------------
//  [*] Public — About page
//
//  What the project is, what it measures and where the data
//  comes from. Static prose — nothing here is fetched. Each
//  coefficient family is named only in passing, because the
//  Coefficients page carries the full explanation of every
//  metric next to its own charts.
//
//  Split into (root component last):
//
//    SECTIONS — the body copy as data
//    Section  — one heading + paragraphs block
//    About    — the page (default export)
//
//  Used by:
//    - router.jsx — route /about (inside PublicPageLayout)
// -----------------------------------------------------------

import { Box, Card, CardContent, Typography } from '@mui/material';







// -----------------------------------------------------------
// SECTIONS
// -----------------------------------------------------------
//
// Editing the About copy is a change to this array; the JSX
// below carries no prose of its own.
// -----------------------------------------------------------

const SECTIONS = [
  {
    title: "What this is",
    paragraphs: [
      "Bitcoin LN Statistics is an analytics platform for the Bitcoin Lightning Network. It collects the network's public topology over time, stores it, and turns it into measurements of how concentrated the network has become — how much of its capacity and how many of its channels sit with how few participants.",
      "It is maintained as a research project at the Faculty of Kaunas, Vilnius University.",
    ],
  },
  {
    title: "What it measures",
    paragraphs: [
      "Two properties are tracked for every node and every entity: degree, the number of channels it holds, and weighted degree, the total capacity of those channels. Everything else is derived from these.",
      "Concentration is reported through several established measures — the Gini coefficient, the Herfindahl-Hirschman Index, the Nakamoto coefficient, Shannon entropy and the Theil index, each in raw and normalized form where that applies — because they disagree in instructive ways: a measure sensitive to the very top of the distribution can move while one sensitive to its middle does not. The Coefficients page explains each of them next to its charts.",
      "Lorenz curves show the same distributions in full rather than as a single number, and the snapshots show how each entity's share has moved over time.",
    ],
  },
  {
    title: "Nodes and entities",
    paragraphs: [
      "A node is one Lightning peer as the network advertises it. An entity is a group of nodes that appear to be operated together. The distinction matters: an operator running many nodes looks decentralized when counted by node and considerably less so when counted by entity, so every metric here is computed both ways.",
    ],
  },
  {
    title: "Where the data comes from",
    paragraphs: [
      "Two independent sources are imported and reconciled. LNResearch provides the historical record of channel announcements, and an LND DBReader export contributes a second view of the same events. The Data Sources page shows how far the two overlap and what each contributes on its own.",
      "Channel funding is confirmed against the Bitcoin blockchain itself through an Electrum server, so capacity figures trace back to on-chain outputs rather than to gossip alone.",
    ],
  },
  {
    title: "Reproducibility",
    paragraphs: [
      "Every chart on this site is a file generated by the processing pipeline, not a rendering of a private query. The same files are downloadable under Raw Data, alongside CSV exports of the underlying entity metrics, so any figure shown here can be checked or recomputed independently.",
    ],
  },
];







// -----------------------------------------------------------
// Section
// -----------------------------------------------------------
//
// A heading and its paragraphs, the body text justified to
// match the Coefficients page.
// -----------------------------------------------------------

function Section({ title, paragraphs }) {
  return (
    <Box className="mb-6 last:mb-0">
      <Typography variant="h6" component="h2" className="mb-2">
        {title}
      </Typography>

      {paragraphs.map((paragraph) => (
        <Typography
          key={paragraph.slice(0, 40)}
          className="mb-2 last:mb-0"
          style={{ textAlign: 'justify' }}
        >
          {paragraph}
        </Typography>
      ))}
    </Box>
  );
}







// -----------------------------------------------------------
// About (default export)
// -----------------------------------------------------------
//
// One card: the page heading, then every SECTIONS entry
// rendered through Section in array order.
//
// Used by:
//   - router.jsx — route /about (inside PublicPageLayout)
// -----------------------------------------------------------

export default function About() {
  return (
    <div className="w-full">
      <Card elevation={1} className="w-full">
        <CardContent>
          <h1>About</h1>

          {SECTIONS.map((section) => (
            <Section
              key={section.title}
              title={section.title}
              paragraphs={section.paragraphs}
            />
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
